### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by tropyx** [tropyx/NetBeansPuppet#1]
Need to add Syntax Highlighting and code completion.

**Comment by Chris2011** [comment]
What about the syntax highlighting? This feature is essential.

**Comment by Chris2011** [comment]
It should look like this: https://redstack.files.wordpress.com/2014/11/docker1.png

**Comment by mkleint** [comment]
You can try installing this nbm - https://github.com/mkleint/NetBeansPuppet/releases/tag/v1.2.1

you should probably be able to do about the same as your screenshot with exception if parameter names which are currently just regular identifier
http://screencast.com/t/MJrfHbOpaCG

**Comment by Chris2011** [comment]
Thx, it works :) Is this only a test or is it good for using? So than you can update the version on the plugin portal or so. Maybe it would be nice to install it via the plugin center right inside netbeans.

**Comment by mkleint** [comment]
i'm using it for months without problems

**Comment by Conzar** [comment]
How does it compare to Geppetto?  I haven't tried this plugin since 2013 so would like to know if the features are now on par with Geppetto?

**Comment by mkleint** [comment]
I've never used Geppetto myself so cannot  compare. The features I've added are mostly editor based and possibly tied to my own puppet setup. improvement requests welcome.

1. coloring
2. hyperlinks to other .pp files
3. project recognized by manifests/site.pp (but this was was already done I believe)
4. puppet lint integration showing warnings/errors in editor. (you need puppet lint on path, might not work on windows, I'm on mac)
5. eyaml files decrypted text view.
6. editor tab shows the module the file belongs to eg. install.pp [ maven ]

**Comment by Conzar** [comment]
So how do you develop puppet modules?  Since puppet modules don't have site.pp.

**Comment by mkleint** [comment]
I don't, I've just scratched my itch. We have puppet modules/ (and our own buildeng-modules/) folders on the same level as manifests/ (+site.pp) folder. Hyperlinks work within the modules/ or buildeng-modules/ folder only I believe.

**Comment by Conzar** [comment]
@mkleint ah, so are you still running the monolithic approach?  Its highly recommended to move away from that and use r10k.  I have spent the last 6 months or so migrating from the monolithic style to the r10k style and couldn't be happier.  If your unsure of r10k, PuppetLabs offers a virtual training course on r10k (I took it more than 6 months ago).

**Comment by Chris2011** [comment]
It would be nice if the develop branch or the new version should be published to netbeans plugin portal or the plugin manager to use it.

**Comment by mkleint** [comment]
@Chris2011 I've filed issue #8 . Currently the nbm cannot be uploaded there due to missing metadata.

**Comment by mkleint** [comment]
@Conzar can you file a separate issue for it with some links? I might be able to check it out sometimes.
