### ISSUE TITLE
After installing the module i cannot create a puppet Project

### ISSUE THREAD

**Issue by koma85** [tropyx/NetBeansPuppet#12]
There s no puppet as a project option
![schermata 2015-09-04 alle 14 45 35](https://cloud.githubusercontent.com/assets/247170/9683801/b6fb429a-5313-11e5-8cd1-53b1acd8d6a2.png)
![schermata 2015-09-04 alle 14 45 50](https://cloud.githubusercontent.com/assets/247170/9683800/b6f73010-5313-11e5-8075-264f3fee1871.png)

**Comment by mkleint** [comment]
Creating new projects is not implemented yet. You need an folder with existing manifests/site.pp to open the project right now. Issue #9 is filed to be able to recognize a pupet module as well (via presence of manifests/init.pp in given folder

**Comment by mkleint** [comment]
there you go - https://github.com/tropyx/NetBeansPuppet/commit/97f99f453956107e7f5ed6b53064f13e3a9bff08
