### ISSUE TITLE
Open an r10k control project

### ISSUE THREAD

**Issue by Conzar** [tropyx/NetBeansPuppet#13]
Fantastic work on opening puppet modules!  The performance of this plugin + netbeans is much better than Geppetto.  The last bit that I need for a complete puppet development environment is to allow opening of a project that is structured for R10K.  Basically, the interesting bits to edit in the IDE are the node definition files (similar to a site.pp) and roles/profiles (which are just normal .pp files)

Here is the structure that I use for a control repository:
```
repo
| --> manifests (directory that contains node definitions --- each file acts like a site.pp)
| --> site
|   | --> profile
|      | --> manifests (a directory that contains directories of profiles)
|   | --> role
|      | --> manifests (a directory that contains directories of roles)
| --> environment.conf (lists the module path ... not important for IDE) 
| --> Puppetfile (r10k file for getting puppet dependencies)
```

To read more on the r10k concept: 
http://garylarizza.com/blog/2014/08/31/r10k-plus-directory-environments/

**Comment by mkleint** [comment]
are there some open source projects with this setup I could check out?

**Comment by Conzar** [comment]
@mkleint Well, I learned about Roles and Profiles from the Puppet Advanced Training (now called Puppet Practitioner).  I picked up r10k after taking the training course specifically on r10k.  There is probably no reason to open source a control repository (especially since most people probably include their hiera data in this repository but IMHO I think its better to have a separate hiera repo).  I did some google'fu and haven't found anything so far.

There are guides of how to setup control repos though.  I also thought this was a pretty nice introduction to the concept of r10k.

https://docs.puppetlabs.com/pe/latest/quick_start_r10k.html

I think though, the easiest solution is to just open up the control repo as if it were a puppet project.  If you scan the files and find *.pp, than just treat it like the puppet module or puppet site like you do already.  What do you think?

**Comment by mkleint** [comment]
well, at project recognition level we cannot do a scan of entire directory or multiple directories. 
What I'm looking for some well known paths relative to the project basedir that would only appear in a puppet project. eg ${basedir}/pom.xml identifies a maven project or ${basedir}/manifests/init.pp identifies a puppet module.

**Comment by Conzar** [comment]
How about scanning for a file in the root directory called Puppetfile?  All control repositories will require this file.

**Comment by mkleint** [comment]
the quickstart  page (and some other pages) always operate with manifests/site.pp being part of the control repository. You don't have that one? can you add a dummy one?

I could try going with Puppetfile, but it's not r10k specific, we  have it in our setup as well. In correct location. I'm wondering in what other contexts the file could be used as well. I'm afraid here of false positives where a wrong directory is marked as puppet project. There's little ways as a user of telling netbeans that the code got it wrong and it could be masking some other, more suitable project type in some cases.

**Comment by Conzar** [comment]
@mkleint adding site.pp works.  I think it should be ok for now.
