### ISSUE TITLE
Unable to open Puppet modules that do not have a site.pp manifest

### ISSUE THREAD

**Issue by erikkugel** [tropyx/NetBeansPuppet#21]
Hi and thanks for this awesome NetBeans module!

I'm maintaining a fairly complex Puppet repository at my work, but many of our modules (most notable all the recent ones) do not contain a site.pp file. That's because we're striving to separate our data from our Puppet code, and we're able to place all that data in Hiera.

Is there an easy solution to allow this NetBeans module to open Puppet modules without a site.pp file in them? I'm not a Java expert, but I can try tweaking https://github.com/tropyx/NetBeansPuppet/blob/0847c82c4b9606204024fb3998dc96b2b9e51dc2/src/main/java/com/tropyx/nb_puppet/PuppetProjectFactory.java unless it's totally against this module's philosophy...

Thanks in advance!

**Comment by mkleint** [comment]
could #13 be related? could you add a dummy site.xml? is there any other standard file we could base the recognition algorithm on?

**Comment by erikkugel** [comment]
Indeed, I was using a temporary empty site.pp (adding and removing it as a hack) up until now, but with a few dozen modules, some having a site.pp and some not, it's very cumbersome to manage (just in order to use NetBeans). If it was only a few modules and only a few users, it would be manageable, but I'm with a huge repo. shared by many users and lots of modules (I know not everyone have this scaling issue). I think that the only real requirement in Puppet to having a module is to have a manifests/init.pp file, and everything else is optional, so why not just check for that and nothing else? (I realize that might be a silly question but I'm not yet all caught up on the plugin code...)

**Comment by mkleint** [comment]
Well, we already should be checking for manifests/init.pp for sure.. if that is not working, I would like to know more details about your setup. I do have many modules with manifests/init.pp that work fine.

can I clone some of your modules someplace?

**Comment by tropyx** [comment]
Hi,

The mechanism it uses for deciding what a "Puppet Project" is "something 
with a site.pp in the directory" as the parameter.  If you want to 
suggest some other logic that might be able to delineate a collection of 
puppet manifests from a bunch of random text files, fire away!

Of course you could always hack around it, create a dummy site.pp just 
to create the project, perhaps add it to git ignore or something so it's 
just on your local NetBeans machine.

Michael.

**Comment by mkleint** [comment]
https://github.com/tropyx/NetBeansPuppet/blob/master/src/main/java/com/tropyx/nb_puppet/PuppetProjectFactory.java should cover both site.pp and init.pp in the latest version

**Comment by erikkugel** [comment]
Hmm, I might be confused, but I would expect that one to be included in the 2.0.1 release from Nov 7, 2015 (since that file was last touched in Sep.), but I'm running NetBeans 8.0.2 with Puppet Configuration Editor 2.0.1, and I still need to touch a manifests/site.pp file to add a module as a project... Am I missing something obvious?

**Comment by Conzar** [comment]
I just want to weigh in.  I develop puppet modules and manage puppet control repos.  For puppet modules, as long as you have a manifest/init.pp, the module will be picked up.

For the control repo, as long as you have a manifests/site.pp, it will also pick it up.

Our control repo's don't have anything in the site.pp, its just an empty file.  The puppet server doesn't complain.
