### ISSUE TITLE
Please add option to set a project to a Puppet project.

### ISSUE THREAD

**Issue by Chris2011** [tropyx/NetBeansPuppet#27]
I have a HTML5 Project and I installed the Puppet Configuration Editor. The problem is, that the project hast a Vagrant.pp and a manifest/site.pp which makes the Project unusable as a HTML5 Project. So I have to deactivate the plugin to have my HTML5 project back again. So please make an option to each project where you find a manifest/site.pp that I can enable Puppet support for explicit this project. If this not make sense, i would prefer to not creating projects, I really would like to use Pupper Syntax Highlighting for pp files but this is not possible with this plugin, because it breaks my other project types.

Regards

Chris

**Comment by Chris2011** [comment]
Maybe it could be good, if it is possible to extends project types.

**Comment by mkleint** [comment]
not sure if this has a solution. this is how netbeans project types were designed and operate. each project factory recognizes a project by something. maven projects by pom.xml for example. so any folder with pom.xml becomes a maven project. what's important though is the ordering of the project factories. that's likely the only thing we can do, make sure the html project type has higher order than puppet.

please note that some puppet file features are bound to puppet project type.

**Comment by Chris2011** [comment]
Is it not possible to merge some 2 project types? Make a HTML5 project to an html5 puppet project for example? You can enable NodeJS inside an HTML5 Project and deactivate it. So you have all HTML5 context sensitive entries and more or different ones for the NodeJS project type. To set order is not good I think. I have the same problem with a package.json and a pom.xml, pom.xml is always winning...

**Comment by mkleint** [comment]
we could provide an abstracted layer of puppet support that would work in designated set of project types (hey have to be known). but that's not going to solve the problem of project type ordering as  we would still need to include the puppet only project type and keep the recognition by files. 

In an ideal world netbeans would provide a feature to let you choose what project type to use for given folder if there are clashes or if you want to override the recognized type. It shouldn't be even that hard to write. I've filed https://netbeans.org/bugzilla/show_bug.cgi?id=269297

**Comment by Chris2011** [comment]
I created such bug too called project type switcher, because I have problems with pom.xml and package.json. Pom always wins and destroy ms HTML5 project: https://netbeans.org/bugzilla/show_bug.cgi?id=246939 and this with the problem: https://netbeans.org/bugzilla/show_bug.cgi?id=256094

**Comment by Chris2011** [comment]
Smth new here?

**Comment by tropyx** [comment]
I know it's not ideal, and a bit of a hacky solution but wouldn't it be a lot easier just to not use those file names in projects you edit in NetBeans?
In the same way Chef uses the erb extension for templates - so instead of /etc/motd you have /etc/motd.erb
As Milos said it's a core function of NetBeans - an analogy that springs to mind is wanting main() to be ignored by a C compiler :-)

**Comment by Chris2011** [comment]
I'm wondering how other IDEs does it, is it really needed to have a whole puppet project? I think only Puppet support for those files is needed and not a whole project. Maybe I'm wrong but yeah, my opinion.

**Comment by Chris2011** [comment]
It is always difficult to have a project type which could be another project type too, I have the problem with a html project with a package.json AND a pom.xml now it is always a maven project, this is a pain in the ass, the html functionality gets lost. I created a ticket, as I mentioned it before. So IMHO, only to have Puppet editor support is enough.

**Comment by Chris2011** [comment]
And will make no trouble with projects.

**Comment by tropyx** [comment]
I think there are a few questions there, let me try and get them...
1. You can just drop a pp file into any other project, and get syntax colouring.
2. Netbeans doesn't have a "general project" (like Eclipse) so you just open/create a folder in Windows->Favourites and put anything you like in it.

**Comment by Chris2011** [comment]
And what are the questions here, I don't get it sry.

You can implement a new language support, without creating a new project type, the question is: Is a real puppet project really needed? You only created a new editor to implement Puppet syntax highlighting. The developer created not only an editor to support the language in NetBeans, he created a whole new project type for puppet, which is, in my opinion not needed, maybe. 

NetBeans has project types and they will be created by for example a package.json or a pom.xml, if those files are not there, you have the nbfolder where the project config is in.

**Comment by tropyx** [comment]
Does there need to be a project type?  Well that just depends on how complex the puppet environment you're working in really.  If you've got a few dozen pp files absolutely.

**Comment by mkleint** [comment]
So if I understand it correctly, you are suggesting to drop the puppet project type and have everyone use some other project types of their choice.

Right now all or close to all puppet modules from the forge can be cloned and worked on without any setup. What setup would be required without the puppet project type?

**Comment by Chris2011** [comment]
Yes I suggested it.

So if a puppet project is really needed, than we need a unique identifier not only an init.pp file in a specific folder, but a defined project folder or smth to identify the puppet project, which is a real puppet project.

So if you have a maven or html5 project with a folder and a init.pp, puppet is always supported BUT it will not convert the project into a puppet project. Maybe a .whatever-folder and .whatever-file to identify. That would be easier. The currect state of it is real problematic, I know it is the case of how netbeans treats the projecttypes but it is not usable anymore with your plugin.

For me atm I only use the Puppet editor, but I have to remove it, because it breaks my projects where some puppet files are in.

Yes dropping the project type is not an option but it is only netbeans who can handle this as a project type, so please find a better, unique identifier to make it as a puppet project.

**Comment by Chris2011** [comment]
Searching for manifest -> init.pp or in general an init.pp to make any project to a puppet project can't be the only option here.

**Comment by Chris2011** [comment]
And if you have existing puppet modules, which are projects, it should be easy to have a project type like Create a puppet project from existing sources.

**Comment by tropyx** [comment]
-- I think I understand what you're saying, but I'm pretty sure removing the existing test and replacing it with a .this-is-a-netbeans-puppet-project style test would end up causing chaos for everyone who has used the module previously, sorry.
-- Is re-architechting the plugin the only real option to solve your problem?  Can't you just move/rename your files around a little to work with the tools you have at hand?  I'm always having to find work-arounds like this, it's a big part of the art of computing.
-- The other option for you is to take a fork of this and customising it for yourself, I can't see many other people hitting this problem.
-- Also, along the lines of what Milos said, as it stands the plugin is written in such a way that it works out of the box with nearly everyone else's Puppet modules from the Puppet Forge, and it's extremely unlikely the Puppet developers are going to include a .nbpuppet-project method just to fit in with our little plugin.  Like I said it's a bit like wanting main() to mean something else to C compilers (I've seen people wanting that too)
-- Thanks for your interest Chris, but it just ain't gunna happen :)

**Comment by Chris2011** [comment]
A lot of discussion for nothing? This is really weird. Our development enviroment is working like that in our company, that process was not build by my own. So then we have to change the whole process in our company only to fit in it. Most of our projects are working like that, you have an init.pp file in it, which will create a puppet project from your plugin which prevents me from using it. This is in general a problem bei NetBeans that it is only using one project type per project at the same time without changing it.

It is a pity to see that we can't find a proper solution for that because I wanted to use it, now I can't this was and is the initial problem.

**Comment by Chris2011** [comment]
I don't want to do a workaround as you said, it should be by the plugin developer to find a workaround that my case works for it too, not vice versa. Why should I have to do a workaround only to use your plugin? This is the wrong way and if you say so:  I'm always having to find work-arounds like this, it's a big part of the art of computing. Then you should find one for the problem.

I linked the ticket from NetBeans with the problem of one project, uses 2 different files which could be a maven or a html5 project, which already exists in NetBeans.

**Comment by mkleint** [comment]
I'm probably personally source of your pain on multiple fronts, I've written the maven project type as well and been long term maintainer of project system at netbeans in general. The auto-recognition of maven's pom.xml files is my fault as well. To my defence I believe the way netbeans supports maven is one of the features that keep it alive. I've spent endless time to argue that a most features should not be project type specific but be able to embed themselves into multiple different project types natively and that less manual configuration and autodiscovery is always better than less.
To  my knowledge (which is way outdated) the number of people with clashing project type folders is fairly small, but unfortunate group penalized by the one folder == one unselectable project type rule that is embedded in the project system.

While I believe the puppet editor support should indeed independent of the project type, maybe even into 2 separate plugins, to be honest I don't plan to work on it myself. I still do believe in autodetection and configuration-less projects, but with 2 separate plugins you would have an option to install just one.

**Comment by Chris2011** [comment]
@mkleint yes that sounds good for me. It is of course a good option to handle that "problem".

As you follow the ticket: https://netbeans.org/bugzilla/show_bug.cgi?id=256094 it is a very long discussion too and we did it via mailing list with geertjan too and no outcome atm.
I know that this problem is a bigger one and some people have it too, not so much maybe. There wouldn't be a problem if each project, where it make sense, can have the same functionality as an other project. The problem for me is, HTML5 Project has different stuff, which i have to use, than a maven project so if NB converts the HTML5 project to maven, I can't use it anymore, because the stuff for the HTML5 project are gone.
Anyway that should be discussed in the original NB ticket.

So at the end, split the plugin to have the Editor support independent from the Project stuff, would be great.

**Comment by tropyx** [comment]
Feel free to drop us a patch Chris.
