### ISSUE TITLE
Support for '->' syntax 

### ISSUE THREAD

**Issue by mariusznet** [tropyx/NetBeansPuppet#5]
Hello,
Using -> in pp files breaks highlighting, also it is impossible to write '-' using keyboard.

**Comment by mkleint** [comment]
what version are you using? with latest master I appear to be able to do both

**Comment by mariusznet** [comment]
Netbeans 8.0.1 and lasted master. 
![example](https://cloud.githubusercontent.com/assets/7955061/6764677/3915819e-cfbd-11e4-89e9-f883661cee67.png)

**Comment by mkleint** [comment]
interesting. I'm not able to write '/' at the position of ->
I suppose we're swallowing the character(s) somewhere (once I add a comment or quote symbol, '/' starts working again..)

**Comment by mkleint** [comment]
could you try building latest https://github.com/mkleint/NetBeansPuppet to check if your problem went away, I've played a bit with operator tokenization logic + fixed regexp handling. Thx.

**Comment by mariusznet** [comment]
Looks like fixed, thx. 

Small issue in new version, comments are incorrectly colored.
![capture](https://cloud.githubusercontent.com/assets/7955061/6771006/f7f13a08-d0d1-11e4-9af7-2e2c6855cf97.PNG)

**Comment by mkleint** [comment]
https://github.com/mkleint/NetBeansPuppet/releases/tag/v1.2.1
should have the fix for multiline comments (was never implemented as we don't use it at work)


pls note that github doesn't allow me to upload a .nbm file (it did 3 days ago) and thus you have to unzip the release file to get the nbm file for installation

**Comment by mariusznet** [comment]
Works like a charm.

Regards,
Mariusz
