### ISSUE TITLE
Toggle Comment

### ISSUE THREAD

**Issue by WallaceTan** [tropyx/NetBeansPuppet#6]
To be able to toggle comment with keyboard shortcuts (ctrl+shift+c or ctrl+/) would be a great feature for this excellent tool!

**Comment by mkleint** [comment]
pls build https://github.com/mkleint/NetBeansPuppet yourself for comment/uncomment (in toolbar but I assume shortcuts work as well).. I'd like to let the change soak a bit before releasing..

**Comment by mkleint** [comment]
released in 1.2.2
https://github.com/tropyx/NetBeansPuppet/releases/tag/v1.2.2
