### ISSUE TITLE
Puppet Module Development Support

### ISSUE THREAD

**Issue by Conzar** [tropyx/NetBeansPuppet#9]
Developing Puppet Modules is a big part of using the Puppet programming language.  I am making the request to support puppet module development similar to how its handled in Geppetto (an eclipse based Puppet IDE).

Here are some links to indicate how it works in eclipse:
https://github.com/puppetlabs/geppetto/blob/dev/docs/4.2/index.md
http://puppetlabs.github.io/geppetto/faq.html#/2011/04/14/gepetto-demo-by-james-turnbull

**Comment by mkleint** [comment]
could you test https://github.com/mkleint/NetBeansPuppet/releases/tag/test1.3 ?

**Comment by mkleint** [comment]
released 1.3 with module support

**Comment by Conzar** [comment]
Awesome @mkleint  I have just tested it (sorry was pretty busy this week).  So modules can now be opened!!!!
